config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :subjects
  resources :students

  root 'top#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
       redirect_to students_path, notice: "#{@student.name}を登録しました"
    else
       render action: :new
    end
  end

  def edit
    @student = find_student_by_id
  end

  def update
    @student = find_student_by_id
    if @student.update(student_params)
       redirect_to students_path, notice: "#{@student.name}を更新しました"
    else
       render action: :edit
    end
  end

  def destroy
    @student = find_student_by_id
    @student.destroy
    redirect_to students_path, notice: "#{@student.name}を削除しました"
  end

  private
  def student_params
    params.require(:student).permit(:name, :number, :subject_id)
  end

  def find_student_by_id
    Student.find(params[:id])
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.all
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
       redirect_to subjects_path, notice: "#{@subject.department}を登録しました"
    else
       render action: :new
    end
  end

  def new
    @subject = Subject.new
  end

  def edit
    @subject = find_subject_by_id
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = find_subject_by_id
    if @subject.update(subject_params)
       redirect_to subjects_path, notice: "#{@subject.department}を更新しました"
    else
       render action: :edit
    end
  end

  def destroy
    @subject = find_subject_by_id
    @subject.destroy
    redirect_to subjects_path, notice: "#{@subject.department}を削除しました"
  end

  private
  def subject_params
    params.require(:subject).permit(:department, :content, :teacher)
  end

  def find_subject_by_id
    Subject.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
    <p>
    <%= f.label(:name, "生徒氏名") %>
    <%= f.text_field :name %>
    </p>
    <p>
    <%= f.label :number, "学籍番号" %>
    <%= f.text_field :number %>
    </p>
    <p>
    <%= f.label :subject_id, "学科ID" %>
    <%= f.text_field :subject_id %>
    </p>
    <%= f.submit "登録" %>
<% end %>

app/views/students/edit.html.erb
<h2>編集</h2>
 
<%= render "form" %>
 
<%= link_to "戻る", students_path %>

app/views/students/index.html.erb
<h1>生徒一覧</h1>
<%= link_to "新規登録", new_student_path %>
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<table border="1">
  <tr>
    <th>生徒氏名</th>
    <th>学籍番号</th>
    <th>学科</th>
    <th>操作</th>
  </tr>
    <% @students.each do |student| %>
      <tr>
      <td><%= student.name %></td>
      <td><%= student.number %></td>
      <td><%= student.subject_id %></td>
      <td>
        <%= link_to "詳細", student %>
        <%= link_to "編集", edit_student_path(student) %>
        <%= link_to "削除", student_path(student), :method => :delete %>
      </td>
      </tr>
    <% end %>
</table>
<%= link_to "トップへ戻る", root_path %>

app/views/students/new.html.erb
<h1>新規登録</h1>
 
<%= render "form" %>
 
<%= link_to "戻る", students_path %>

app/views/students/show.html.erb
<h1>生徒詳細</h1>
<table border="1">
  <tr>
    <th>生徒氏名</th>
    <th>学籍番号</th>
    <th>学科名称</th>
  </tr>
  <tr>
    <td><%= @student.name %></td>
    <td><%= @student.number %></td>
    <td><%= @student.subject_id %></td>
  </tr>
</table>
<%= link_to "戻る", :back %>

app/views/subjects/_form.html.erb
<%= form_for @subject do |f| %>
    <p>
    <%= f.label(:department, "名称") %>
    <%= f.text_field :department %>
    </p>
    <p>
    <%= f.label :content, "説明" %>
    <%= f.text_field :content %>
    </p>
    <p>
    <%= f.label :teacher, "担当教師" %>
    <%= f.text_field :teacher %>
    </p>
    <%= f.submit "登録" %>
<% end %>

app/views/subjects/edit.html.erb
<h2>編集</h2>
 
<%= render "form" %>
 
<%= link_to "戻る", subjects_path %>

app/views/subjects/index.html.erb
<h1>学科一覧</h1>
<%= link_to "新規登録", new_subject_path %>
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<table border="1">
  <tr>
    <th>学科</th>
    <th>学科説明</th>
    <th>担当教師</th>
    <th>操作</th>
  </tr>
    <% @subjects.each do |subject| %>
      <tr>
      <td><%= subject.department %></td>
      <td><%= subject.content %></td>
      <td><%= subject.teacher %></td>
      <td>
        <%= link_to "詳細", subject %>
        <%= link_to "編集", edit_subject_path(subject) %>
        <%= link_to "削除", subject_path(subject), :method => :delete %>
      </td>
      </tr>
    <% end %>
</table>
<%= link_to "トップへ戻る", root_path %>

app/views/subjects/new.html.erb
<h1>新規登録</h1>
 
<%= render "form" %>
 
<%= link_to "戻る", subjects_path %>

app/views/subjects/show.html.erb
<h1>学科詳細</h1>
<table border="1">
  <tr>
    <th>学科</th>
    <th>学科説明</th>
    <th>担当教師</th>
  </tr>
  <tr>
    <td><%= @subject.department %></td>
    <td><%= @subject.content %></td>
    <td><%= @subject.teacher %></td>
  </tr>
</table>
<%= link_to "戻る", :back %>

app/views/top/index.html.erb
<h1>school アプリ</h1>
<%= link_to "生徒一覧へ", students_path %>
<%= link_to "学科一覧へ", subjects_path %>